---
products:
  -
    code: 001
    name: "Travel Card Holder"
    price: 10.00

  -
    code: 002
    name: "Personalised Cufflinks"
    price: 20.00

  -
    code: 003
    name: "Kids T-Shirt"
    price: 30.00

  -
    code: 004
    name: "Test Product"
    price: 5.00